name: finance-app

services:
  swagger:
    build: swagger-ui
    image: swagger-finance:1.0.5
    ports:
      - 81:8080
    networks:
      - finance-network
  pg_db:
    build: postgresql
    image: postgresql-finance:1.0.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 508an375
    networks:
      - finance-network
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres
      PGADMIN_DEFAULT_PASSWORD: 508an375
    ports:
      - 82:80
    networks:
      - finance-network
  proxy:
    build: proxy
    image: proxy-finance:1.0.0
    ports:
      - 80:80
    networks:
      - finance-network
  user-service:
    build: user-service
    image: user-service-finance:1.0.0
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - finance-network
  audit-service:
    build: classifier-service
    image: classifier-service-finance:1.0.0
    networks:
      - finance-network

networks:
  finance-network: